# Generated by Django 3.1.7 on 2021-03-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210311_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
    ]
