# Generated by Django 3.1.7 on 2021-03-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_l',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_m',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_s',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xl',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xs',
            field=models.IntegerField(default='5'),
        ),
    ]
