# Generated by Django 3.1.7 on 2021-03-14 20:17

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210314_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('XS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large')], max_length=11, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_per_size', models.IntegerField(default='5')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsize')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(through='products.ProductStock', to='products.ProductSize'),
        ),
    ]
